from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

from ashare_agent.models import LimitUpEvent, SectorSnapshot, SectorType, StockSnapshot


CN_TZ = ZoneInfo("Asia/Shanghai")


class MockMarketDataProvider:
    """Deterministic market data for tests, demos, and contract development."""

    def __init__(self, as_of: datetime | None = None) -> None:
        self.as_of = as_of or datetime(2026, 7, 14, 14, 45, tzinfo=CN_TZ)

    def get_sector_snapshots(self) -> list[SectorSnapshot]:
        return [
            SectorSnapshot(
                sector_id="concept_pcb",
                sector_name="PCB",
                sector_type=SectorType.CONCEPT,
                timestamp=self.as_of,
                pct_change=5.18,
                main_net_inflow=12_992_000_000,
                amount=91_800_000_000,
                amount_growth=0.68,
                up_count=42,
                down_count=6,
                limit_up_count=7,
                new_high_count=11,
                breadth=0.875,
                top_symbols=["300476.SZ", "002916.SZ", "603228.SH"],
                continuity_days=3,
                catalyst_strength=76,
                board_open_rate=0.18,
                tail_support=82,
            ),
            SectorSnapshot(
                sector_id="concept_cpo",
                sector_name="CPO",
                sector_type=SectorType.CONCEPT,
                timestamp=self.as_of,
                pct_change=3.62,
                main_net_inflow=6_730_000_000,
                amount=72_500_000_000,
                amount_growth=0.34,
                up_count=31,
                down_count=13,
                limit_up_count=3,
                new_high_count=5,
                breadth=0.704,
                top_symbols=["300308.SZ", "300394.SZ"],
                continuity_days=2,
                catalyst_strength=61,
                board_open_rate=0.29,
                tail_support=66,
            ),
            SectorSnapshot(
                sector_id="concept_consumer",
                sector_name="消费电子",
                sector_type=SectorType.CONCEPT,
                timestamp=self.as_of,
                pct_change=-0.84,
                main_net_inflow=-3_420_000_000,
                amount=58_900_000_000,
                amount_growth=-0.21,
                up_count=15,
                down_count=39,
                limit_up_count=1,
                new_high_count=1,
                breadth=0.278,
                top_symbols=["002475.SZ"],
                continuity_days=0,
                catalyst_strength=28,
                board_open_rate=0.47,
                tail_support=31,
            ),
        ]

    def get_stock_snapshots(self) -> list[StockSnapshot]:
        return [
            StockSnapshot(
                symbol="300476.SZ",
                name="胜宏科技",
                timestamp=self.as_of,
                price=118.4,
                pct_change=19.99,
                open=101.2,
                high=118.4,
                low=100.6,
                prev_close=98.67,
                volume=84_200_000,
                amount=9_220_000_000,
                turnover_rate=12.1,
                main_net_inflow=1_680_000_000,
                large_order_net_inflow=940_000_000,
                super_large_order_net_inflow=620_000_000,
                limit_up=True,
                sealed_amount=1_210_000_000,
                board_open_count=0,
                recent_5d_gain=48.2,
                market_cap=101_000_000_000,
                sector_names=["PCB", "AI算力"],
            ),
            StockSnapshot(
                symbol="002916.SZ",
                name="深南电路",
                timestamp=self.as_of,
                price=116.8,
                pct_change=6.2,
                open=110.9,
                high=119.1,
                low=109.6,
                prev_close=109.99,
                volume=33_700_000,
                amount=3_910_000_000,
                turnover_rate=6.3,
                main_net_inflow=720_000_000,
                large_order_net_inflow=410_000_000,
                super_large_order_net_inflow=190_000_000,
                recent_5d_gain=13.4,
                market_cap=59_900_000_000,
                sector_names=["PCB", "AI算力"],
            ),
            StockSnapshot(
                symbol="603228.SH",
                name="景旺电子",
                timestamp=self.as_of,
                price=36.18,
                pct_change=4.6,
                open=34.7,
                high=36.8,
                low=34.4,
                prev_close=34.59,
                volume=48_300_000,
                amount=1_710_000_000,
                turnover_rate=5.8,
                main_net_inflow=260_000_000,
                large_order_net_inflow=130_000_000,
                super_large_order_net_inflow=74_000_000,
                recent_5d_gain=8.1,
                market_cap=30_200_000_000,
                sector_names=["PCB", "消费电子"],
            ),
            StockSnapshot(
                symbol="300308.SZ",
                name="中际旭创",
                timestamp=self.as_of,
                price=246.3,
                pct_change=7.8,
                open=230.2,
                high=249.5,
                low=228.7,
                prev_close=228.48,
                volume=41_000_000,
                amount=10_090_000_000,
                turnover_rate=5.1,
                main_net_inflow=860_000_000,
                large_order_net_inflow=520_000_000,
                super_large_order_net_inflow=310_000_000,
                recent_5d_gain=28.6,
                market_cap=276_000_000_000,
                sector_names=["CPO", "AI算力"],
            ),
            StockSnapshot(
                symbol="300394.SZ",
                name="天孚通信",
                timestamp=self.as_of,
                price=126.7,
                pct_change=3.1,
                open=123.6,
                high=129.2,
                low=122.4,
                prev_close=122.89,
                volume=19_900_000,
                amount=2_510_000_000,
                turnover_rate=4.8,
                main_net_inflow=190_000_000,
                large_order_net_inflow=92_000_000,
                super_large_order_net_inflow=48_000_000,
                recent_5d_gain=9.7,
                market_cap=70_400_000_000,
                sector_names=["CPO"],
            ),
            StockSnapshot(
                symbol="002475.SZ",
                name="立讯精密",
                timestamp=self.as_of,
                price=39.12,
                pct_change=-1.2,
                open=39.8,
                high=40.1,
                low=38.6,
                prev_close=39.59,
                volume=78_400_000,
                amount=3_070_000_000,
                turnover_rate=1.1,
                main_net_inflow=-310_000_000,
                large_order_net_inflow=-210_000_000,
                super_large_order_net_inflow=-90_000_000,
                recent_5d_gain=-4.2,
                market_cap=281_000_000_000,
                sector_names=["消费电子"],
            ),
        ]

    def get_limit_up_events(self) -> list[LimitUpEvent]:
        return [
            LimitUpEvent(
                symbol="300476.SZ",
                name="胜宏科技",
                sector_name="PCB",
                timestamp=self.as_of,
                first_limit_time="10:14:26",
                consecutive_boards=2,
                sealed_amount=1_210_000_000,
            ),
            LimitUpEvent(
                symbol="605058.SH",
                name="澳弘电子",
                sector_name="PCB",
                timestamp=self.as_of,
                first_limit_time="09:47:12",
                consecutive_boards=1,
                sealed_amount=410_000_000,
            ),
        ]
